import sequelize from "../config/connections.js"; 
import Car from "../models/Car.js"; 

export const seedCars = async () => {
  try {
    console.log("Seeding cars...");
    // await sequelize.sync({ force: true });
    // sequelize.sync({ alter: true });
    //  to reset the database 
    // This will run into a problem on the first run, and maybe even once restarting the server after that...
    // Alternatively, open up postgress manually and delete the table there
    await sequelize.sync();
    console.log("✅ Database synced!");

    if (!Car) {
      throw new Error("❌ Car model is undefined! Check the import path.");
    }

    const existingCars = await Car.findAll();
    if (existingCars.length > 0) {
      console.log("✅ Car database already seeded.");
      return;
    }

    const carsData = [
      {
        vin: "1HGCM82633A123456",
        make: "Honda",
        model: "Accord",
        year: 2020,
        mileage: 25000,
        engine: "2.4L I4",
        transmission: "Automatic",
        interior_color: "Black",
        exterior_color: "Blue",
        description: "A reliable sedan with great fuel economy and a comfortable ride.",
        fuel_eco_highway: 34,
        fuel_eco_city: 26,
        price: 22000,
        image_url_1: "https://example.com/car1.jpg",
        image_url_2: "https://example.com/car1-2.jpg",
      },
      {
        vin: "1FMCU0J98FUC12345",
        make: "Ford",
        model: "Escape",
        year: 2021,
        mileage: 18000,
        engine: "1.5L EcoBoost",
        transmission: "Automatic",
        interior_color: "Gray",
        exterior_color: "Red",
        description: "Compact SUV with all-wheel drive and excellent fuel efficiency.",
        fuel_eco_highway: 30,
        fuel_eco_city: 23,
        price: 25000,
        image_url_1: "https://example.com/car2.jpg",
        image_url_2: "https://example.com/car2-2.jpg",
      },
      {
        vin: "WA1LAAF76JD123456",
        make: "Audi",
        model: "Q5",
        year: 2019,
        mileage: 30000,
        engine: "2.0L Turbo",
        transmission: "Automatic",
        interior_color: "Beige",
        exterior_color: "White",
        description: "Luxury SUV with a premium interior and advanced technology.",
        fuel_eco_highway: 28,
        fuel_eco_city: 20,
        price: 35000,
        image_url_1: "https://example.com/car3.jpg",
        image_url_2: "https://example.com/car3-2.jpg",
      },
      {
        vin: "2C4RC1BG0FR123456",
        make: "Chrysler",
        model: "Pacifica",
        year: 2020,
        mileage: 15000,
        engine: "3.6L V6",
        transmission: "Automatic",
        interior_color: "Tan",
        exterior_color: "Silver",
        description: "Spacious minivan with seating for 7 and a smooth ride.",
        fuel_eco_highway: 28,
        fuel_eco_city: 19,
        price: 27000,
        image_url_1: "https://example.com/car4.jpg",
        image_url_2: "https://example.com/car4-2.jpg",
      },
      {
        vin: "3VW5B7AU2HM123456",
        make: "Volkswagen",
        model: "Golf",
        year: 2018,
        mileage: 40000,
        engine: "1.8L I4",
        transmission: "Manual",
        interior_color: "Black",
        exterior_color: "Green",
        description: "Compact hatchback with sporty handling and excellent fuel economy.",
        fuel_eco_highway: 34,
        fuel_eco_city: 26,
        price: 16000,
        image_url_1: "https://example.com/car5.jpg",
        image_url_2: "https://example.com/car5-2.jpg",
      },
      {
        vin: "1FAFP45X2YF123456",
        make: "Ford",
        model: "Mustang",
        year: 2019,
        mileage: 18000,
        engine: "5.0L V8",
        transmission: "Manual",
        interior_color: "Red",
        exterior_color: "Black",
        description: "A powerful muscle car with a roaring V8 engine.",
        fuel_eco_highway: 24,
        fuel_eco_city: 15,
        price: 35000,
        image_url_1: "https://example.com/mustang1.jpg",
        image_url_2: "https://example.com/mustang2.jpg",
      },
      {
        vin: "1HGCV1F30JA123456",
        make: "Honda",
        model: "Civic",
        year: 2021,
        mileage: 15000,
        engine: "1.5L Turbo I4",
        transmission: "CVT",
        interior_color: "Gray",
        exterior_color: "White",
        description: "A fuel-efficient compact sedan with modern tech features.",
        fuel_eco_highway: 40,
        fuel_eco_city: 32,
        price: 24000,
        image_url_1: "https://example.com/civic1.jpg",
        image_url_2: "https://example.com/civic2.jpg",
      },
      {
        vin: "1FA6P8TH5L1234567",
        make: "Ford",
        model: "Fusion",
        year: 2020,
        mileage: 30000,
        engine: "2.0L I4 Turbo",
        transmission: "Automatic",
        interior_color: "Beige",
        exterior_color: "Silver",
        description: "A comfortable midsize sedan with a smooth ride.",
        fuel_eco_highway: 31,
        fuel_eco_city: 23,
        price: 21000,
        image_url_1: "https://example.com/fusion1.jpg",
        image_url_2: "https://example.com/fusion2.jpg",
      },
      {
        vin: "3FA6P0H76JR123456",
        make: "Ford",
        model: "Escape",
        year: 2022,
        mileage: 12000,
        engine: "1.5L I3 Turbo",
        transmission: "Automatic",
        interior_color: "Black",
        exterior_color: "Blue",
        description: "A compact SUV with advanced safety features and a stylish design.",
        fuel_eco_highway: 33,
        fuel_eco_city: 28,
        price: 29000,
        image_url_1: "https://example.com/escape1.jpg",
        image_url_2: "https://example.com/escape2.jpg",
      },
      {
        vin: "5J6RW2H86JL123456",
        make: "Honda",
        model: "CR-V",
        year: 2021,
        mileage: 22000,
        engine: "1.5L Turbo I4",
        transmission: "CVT",
        interior_color: "Black",
        exterior_color: "Red",
        description: "A spacious and fuel-efficient SUV with a comfortable interior.",
        fuel_eco_highway: 34,
        fuel_eco_city: 28,
        price: 32000,
        image_url_1: "https://example.com/crv1.jpg",
        image_url_2: "https://example.com/crv2.jpg",
      },
      {
        vin: "JM3KFBDM7L0123456",
        make: "Mazda",
        model: "CX-5",
        year: 2021,
        mileage: 18000,
        engine: "2.5L I4",
        transmission: "Automatic",
        interior_color: "Black",
        exterior_color: "Red",
        description: "A stylish and sporty compact SUV with great handling.",
        fuel_eco_highway: 31,
        fuel_eco_city: 25,
        price: 29000,
        image_url_1: "https://example.com/cx5-1.jpg",
        image_url_2: "https://example.com/cx5-2.jpg",
      },
      {
        vin: "4T1BF1FK8JU123456",
        make: "Toyota",
        model: "Camry",
        year: 2020,
        mileage: 22000,
        engine: "2.5L I4",
        transmission: "Automatic",
        interior_color: "Gray",
        exterior_color: "Blue",
        description: "A reliable midsize sedan with excellent fuel economy.",
        fuel_eco_highway: 39,
        fuel_eco_city: 28,
        price: 25000,
        image_url_1: "https://example.com/camry-1.jpg",
        image_url_2: "https://example.com/camry-2.jpg",
      },
      {
        vin: "5TDDZRFH0KS123456",
        make: "Toyota",
        model: "Highlander",
        year: 2019,
        mileage: 28000,
        engine: "3.5L V6",
        transmission: "Automatic",
        interior_color: "Beige",
        exterior_color: "White",
        description: "A spacious 3-row SUV with advanced safety features.",
        fuel_eco_highway: 27,
        fuel_eco_city: 20,
        price: 34000,
        image_url_1: "https://example.com/highlander-1.jpg",
        image_url_2: "https://example.com/highlander-2.jpg",
      },
      {
        vin: "JM1BPBJX2L0123456",
        make: "Mazda",
        model: "Mazda3",
        year: 2022,
        mileage: 12000,
        engine: "2.5L Turbo I4",
        transmission: "Automatic",
        interior_color: "Black",
        exterior_color: "Gray",
        description: "A sporty compact sedan with a premium interior and turbocharged performance.",
        fuel_eco_highway: 33,
        fuel_eco_city: 26,
        price: 27000,
        image_url_1: "https://example.com/mazda3-1.jpg",
        image_url_2: "https://example.com/mazda3-2.jpg",
      },
      {
        vin: "JTDKARFP5L3134567",
        make: "Toyota",
        model: "Prius",
        year: 2021,
        mileage: 15000,
        engine: "1.8L I4 Hybrid",
        transmission: "CVT",
        interior_color: "Gray",
        exterior_color: "Silver",
        description: "A fuel-efficient hybrid hatchback with a quiet and smooth ride.",
        fuel_eco_highway: 50,
        fuel_eco_city: 54,
        price: 26000,
        image_url_1: "https://example.com/prius-1.jpg",
        image_url_2: "https://example.com/prius-2.jpg",
      },
      {
        vin: "1N4BL4CV1LC123456",
        make: "Nissan",
        model: "Altima",
        year: 2021,
        mileage: 20000,
        engine: "2.5L I4",
        transmission: "Automatic",
        interior_color: "Black",
        exterior_color: "Silver",
        description: "A comfortable midsize sedan with modern tech and great fuel efficiency.",
        fuel_eco_highway: 37,
        fuel_eco_city: 28,
        price: 24000,
        image_url_1: "https://example.com/altima-1.jpg",
        image_url_2: "https://example.com/altima-2.jpg",
      },
      {
        vin: "3GNAXKEV3LS123456",
        make: "Chevrolet",
        model: "Equinox",
        year: 2020,
        mileage: 25000,
        engine: "1.5L Turbo I4",
        transmission: "Automatic",
        interior_color: "Gray",
        exterior_color: "Blue",
        description: "A compact SUV with a spacious interior and advanced safety features.",
        fuel_eco_highway: 30,
        fuel_eco_city: 25,
        price: 27000,
        image_url_1: "https://example.com/equinox-1.jpg",
        image_url_2: "https://example.com/equinox-2.jpg",
      },
      {
        vin: "1G1FB1RX6L0123456",
        make: "Chevrolet",
        model: "Camaro",
        year: 2021,
        mileage: 15000,
        engine: "2.0L Turbo I4",
        transmission: "Manual",
        interior_color: "Black",
        exterior_color: "Red",
        description: "A powerful and stylish sports car with thrilling performance.",
        fuel_eco_highway: 30,
        fuel_eco_city: 22,
        price: 33000,
        image_url_1: "https://example.com/camaro-1.jpg",
        image_url_2: "https://example.com/camaro-2.jpg",
      },
      {
        vin: "5N1AT2MV4LC123456",
        make: "Nissan",
        model: "Rogue",
        year: 2020,
        mileage: 23000,
        engine: "2.5L I4",
        transmission: "CVT",
        interior_color: "Beige",
        exterior_color: "White",
        description: "A compact SUV with a comfortable ride and a spacious cabin.",
        fuel_eco_highway: 33,
        fuel_eco_city: 26,
        price: 26000,
        image_url_1: "https://example.com/rogue-1.jpg",
        image_url_2: "https://example.com/rogue-2.jpg",
      },
      {
        vin: "1GCPWBEH4LZ123456",
        make: "Chevrolet",
        model: "Silverado 1500",
        year: 2019,
        mileage: 40000,
        engine: "5.3L V8",
        transmission: "Automatic",
        interior_color: "Black",
        exterior_color: "Gray",
        description: "A powerful full-size truck with towing capability and modern tech.",
        fuel_eco_highway: 23,
        fuel_eco_city: 17,
        price: 35000,
        image_url_1: "https://example.com/silverado-1.jpg",
        image_url_2: "https://example.com/silverado-2.jpg",
      },
    ];

    await Car.bulkCreate(carsData);

    console.log("✅ Car database seeded successfully!");
  } catch (error) {
    console.error("❌ Error seeding cars:", error);
  }
};
